// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv7MM_RhmY7Qc1yfvk71C-5LemhyP3DzM',
    appId: '1:224013550733:web:59e66797f99b77827a4ec4',
    messagingSenderId: '224013550733',
    projectId: 'pokedex-flutter-cbf26',
    authDomain: 'pokedex-flutter-cbf26.firebaseapp.com',
    storageBucket: 'pokedex-flutter-cbf26.appspot.com',
    measurementId: 'G-2T2E6WF60K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQclxpv4U6NWaHLInwFzfCBTL9dDIBxAc',
    appId: '1:224013550733:android:5e892713488e51307a4ec4',
    messagingSenderId: '224013550733',
    projectId: 'pokedex-flutter-cbf26',
    storageBucket: 'pokedex-flutter-cbf26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7DhVNx48Uxa5LuiXXOmElmprWZ2kJLo4',
    appId: '1:224013550733:ios:16b6abd056a48a507a4ec4',
    messagingSenderId: '224013550733',
    projectId: 'pokedex-flutter-cbf26',
    storageBucket: 'pokedex-flutter-cbf26.appspot.com',
    iosClientId: '224013550733-30c04m5s267n0a9qigucfb5lojjvrpqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7DhVNx48Uxa5LuiXXOmElmprWZ2kJLo4',
    appId: '1:224013550733:ios:caf6c0e2027320b27a4ec4',
    messagingSenderId: '224013550733',
    projectId: 'pokedex-flutter-cbf26',
    storageBucket: 'pokedex-flutter-cbf26.appspot.com',
    iosClientId: '224013550733-dj9ns5c2742q9o8gll0sehcmkatqdcr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile.RunnerTests',
  );
}
